routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/monitor', 'HomeController@monitor');

    Route::get('/download/{doc_id}', 'DocumentsController@downloadZip');
    Route::post('/add_file', 'DocumentsController@addFile');
	Route::post('/add_file_jur', 'DocumentsController@add_jur_File');
	Route::post('/add_file_jur2', 'DocumentsController@add_jur_File2');
    Route::get('/delete_file/{file_id}/{doc_number}', 'DocumentsController@deleteFile');
	Route::get('/delete_jur_file/{file_id}/{doc_number}', 'DocumentsController@deleteJurFile');
	Route::get('/delete_jur_file2/{file_id}/{doc_number}', 'DocumentsController@deleteJurFile2');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Cities
    Route::delete('cities/destroy', 'CitiesController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CitiesController');

    // Districts
    Route::delete('districts/destroy', 'DistrictsController@massDestroy')->name('districts.massDestroy');
    Route::resource('districts', 'DistrictsController');

    // Goals
    Route::delete('goals/destroy', 'GoalController@massDestroy')->name('goals.massDestroy');
    Route::resource('goals', 'GoalController');

    // Fond Categories
    Route::delete('fond-categories/destroy', 'FondCategoryController@massDestroy')->name('fond-categories.massDestroy');
    Route::resource('fond-categories', 'FondCategoryController');

    // Object Groups
    Route::delete('object-groups/destroy', 'ObjectGroupController@massDestroy')->name('object-groups.massDestroy');
    Route::resource('object-groups', 'ObjectGroupController');

    // Object Types
    Route::delete('object-types/destroy', 'ObjectTypeController@massDestroy')->name('object-types.massDestroy');
    Route::resource('object-types', 'ObjectTypeController');

    // Documents
    Route::delete('documents/destroy', 'DocumentsController@massDestroy')->name('documents.massDestroy');
    Route::post('documents/media', 'DocumentsController@storeMedia')->name('documents.storeMedia');
    Route::post('documents/ckmedia', 'DocumentsController@storeCKEditorImages')->name('documents.storeCKEditorImages');
	Route::any('/documents/ajax-docs', 'DocumentsController@ajax_docs');
    Route::resource('documents', 'DocumentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Http/Controllers/Admin/ObjectTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyObjectTypeRequest;
use App\Http\Requests\StoreObjectTypeRequest;
use App\Http\Requests\UpdateObjectTypeRequest;
use App\Models\ObjectType;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ObjectTypeController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('object_type_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $objectTypes = ObjectType::all();

        return view('admin.objectTypes.index', compact('objectTypes'));
    }

    public function create()
    {
        abort_if(Gate::denies('object_type_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.objectTypes.create');
    }

    public function store(StoreObjectTypeRequest $request)
    {
        $objectType = ObjectType::create($request->all());

        return redirect()->route('admin.object-types.index');
    }

    public function edit(ObjectType $objectType)
    {
        abort_if(Gate::denies('object_type_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.objectTypes.edit', compact('objectType'));
    }

    public function update(UpdateObjectTypeRequest $request, ObjectType $objectType)
    {
        $objectType->update($request->all());

        return redirect()->route('admin.object-types.index');
    }

    public function show(ObjectType $objectType)
    {
        abort_if(Gate::denies('object_type_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.objectTypes.show', compact('objectType'));
    }

    public function destroy(ObjectType $objectType)
    {
        abort_if(Gate::denies('object_type_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $objectType->delete();

        return back();
    }

    public function massDestroy(MassDestroyObjectTypeRequest $request)
    {
        ObjectType::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/objectTypes/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.objectType.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.object-types.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.objectType.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.objectType.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/objectTypes/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.objectType.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.object-types.update", [$objectType->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.objectType.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $objectType->name) }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.objectType.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/objectTypes/index.blade.php
@extends('layouts.admin')
@section('content')
@can('object_type_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.object-types.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.objectType.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.objectType.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-ObjectType">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.objectType.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.objectType.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($objectTypes as $key => $objectType)
                        <tr data-entry-id="{{ $objectType->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $objectType->id ?? '' }}
                            </td>
                            <td>
                                {{ $objectType->name ?? '' }}
                            </td>
                            <td>
                                @can('object_type_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.object-types.show', $objectType->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('object_type_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.object-types.edit', $objectType->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('object_type_delete')
                                    <form action="{{ route('admin.object-types.destroy', $objectType->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('object_type_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.object-types.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-ObjectType:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/objectTypes/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.objectType.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.object-types.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.objectType.fields.id') }}
                        </th>
                        <td>
                            {{ $objectType->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.objectType.fields.name') }}
                        </th>
                        <td>
                            {{ $objectType->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.object-types.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection