routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/monitor', 'HomeController@monitor');

    Route::get('/download/{doc_id}', 'DocumentsController@downloadZip');
    Route::post('/add_file', 'DocumentsController@addFile');
	Route::post('/add_file_jur', 'DocumentsController@add_jur_File');
	Route::post('/add_file_jur2', 'DocumentsController@add_jur_File2');
    Route::get('/delete_file/{file_id}/{doc_number}', 'DocumentsController@deleteFile');
	Route::get('/delete_jur_file/{file_id}/{doc_number}', 'DocumentsController@deleteJurFile');
	Route::get('/delete_jur_file2/{file_id}/{doc_number}', 'DocumentsController@deleteJurFile2');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Cities
    Route::delete('cities/destroy', 'CitiesController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CitiesController');

    // Districts
    Route::delete('districts/destroy', 'DistrictsController@massDestroy')->name('districts.massDestroy');
    Route::resource('districts', 'DistrictsController');

    // Goals
    Route::delete('goals/destroy', 'GoalController@massDestroy')->name('goals.massDestroy');
    Route::resource('goals', 'GoalController');

    // Fond Categories
    Route::delete('fond-categories/destroy', 'FondCategoryController@massDestroy')->name('fond-categories.massDestroy');
    Route::resource('fond-categories', 'FondCategoryController');

    // Object Groups
    Route::delete('object-groups/destroy', 'ObjectGroupController@massDestroy')->name('object-groups.massDestroy');
    Route::resource('object-groups', 'ObjectGroupController');

    // Object Types
    Route::delete('object-types/destroy', 'ObjectTypeController@massDestroy')->name('object-types.massDestroy');
    Route::resource('object-types', 'ObjectTypeController');

    // Documents
    Route::delete('documents/destroy', 'DocumentsController@massDestroy')->name('documents.massDestroy');
    Route::post('documents/media', 'DocumentsController@storeMedia')->name('documents.storeMedia');
    Route::post('documents/ckmedia', 'DocumentsController@storeCKEditorImages')->name('documents.storeCKEditorImages');
	Route::any('/documents/ajax-docs', 'DocumentsController@ajax_docs');
    Route::resource('documents', 'DocumentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/FondCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class FondCategory extends Model
{
    use SoftDeletes;

    public $table = 'fond_categories';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/FondCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyFondCategoryRequest;
use App\Http\Requests\StoreFondCategoryRequest;
use App\Http\Requests\UpdateFondCategoryRequest;
use App\Models\FondCategory;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class FondCategoryController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('fond_category_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $fondCategories = FondCategory::all();

        return view('admin.fondCategories.index', compact('fondCategories'));
    }

    public function create()
    {
        abort_if(Gate::denies('fond_category_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.fondCategories.create');
    }

    public function store(StoreFondCategoryRequest $request)
    {
        $fondCategory = FondCategory::create($request->all());

        return redirect()->route('admin.fond-categories.index');
    }

    public function edit(FondCategory $fondCategory)
    {
        abort_if(Gate::denies('fond_category_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.fondCategories.edit', compact('fondCategory'));
    }

    public function update(UpdateFondCategoryRequest $request, FondCategory $fondCategory)
    {
        $fondCategory->update($request->all());

        return redirect()->route('admin.fond-categories.index');
    }

    public function show(FondCategory $fondCategory)
    {
        abort_if(Gate::denies('fond_category_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.fondCategories.show', compact('fondCategory'));
    }

    public function destroy(FondCategory $fondCategory)
    {
        abort_if(Gate::denies('fond_category_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $fondCategory->delete();

        return back();
    }

    public function massDestroy(MassDestroyFondCategoryRequest $request)
    {
        FondCategory::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/fondCategories/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.fondCategory.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.fond-categories.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.fondCategory.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.fondCategory.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/fondCategories/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.fondCategory.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.fond-categories.update", [$fondCategory->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.fondCategory.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $fondCategory->name) }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.fondCategory.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/fondCategories/index.blade.php
@extends('layouts.admin')
@section('content')
@can('fond_category_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.fond-categories.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.fondCategory.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.fondCategory.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-FondCategory">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.fondCategory.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.fondCategory.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($fondCategories as $key => $fondCategory)
                        <tr data-entry-id="{{ $fondCategory->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $fondCategory->id ?? '' }}
                            </td>
                            <td>
                                {{ $fondCategory->name ?? '' }}
                            </td>
                            <td>
                                @can('fond_category_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.fond-categories.show', $fondCategory->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('fond_category_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.fond-categories.edit', $fondCategory->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('fond_category_delete')
                                    <form action="{{ route('admin.fond-categories.destroy', $fondCategory->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('fond_category_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.fond-categories.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-FondCategory:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/fondCategories/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.fondCategory.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.fond-categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.fondCategory.fields.id') }}
                        </th>
                        <td>
                            {{ $fondCategory->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.fondCategory.fields.name') }}
                        </th>
                        <td>
                            {{ $fondCategory->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.fond-categories.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection