routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/monitor', 'HomeController@monitor');

    Route::get('/download/{doc_id}', 'DocumentsController@downloadZip');
    Route::post('/add_file', 'DocumentsController@addFile');
	Route::post('/add_file_jur', 'DocumentsController@add_jur_File');
	Route::post('/add_file_jur2', 'DocumentsController@add_jur_File2');
    Route::get('/delete_file/{file_id}/{doc_number}', 'DocumentsController@deleteFile');
	Route::get('/delete_jur_file/{file_id}/{doc_number}', 'DocumentsController@deleteJurFile');
	Route::get('/delete_jur_file2/{file_id}/{doc_number}', 'DocumentsController@deleteJurFile2');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Cities
    Route::delete('cities/destroy', 'CitiesController@massDestroy')->name('cities.massDestroy');
    Route::resource('cities', 'CitiesController');

    // Districts
    Route::delete('districts/destroy', 'DistrictsController@massDestroy')->name('districts.massDestroy');
    Route::resource('districts', 'DistrictsController');

    // Goals
    Route::delete('goals/destroy', 'GoalController@massDestroy')->name('goals.massDestroy');
    Route::resource('goals', 'GoalController');

    // Fond Categories
    Route::delete('fond-categories/destroy', 'FondCategoryController@massDestroy')->name('fond-categories.massDestroy');
    Route::resource('fond-categories', 'FondCategoryController');

    // Object Groups
    Route::delete('object-groups/destroy', 'ObjectGroupController@massDestroy')->name('object-groups.massDestroy');
    Route::resource('object-groups', 'ObjectGroupController');

    // Object Types
    Route::delete('object-types/destroy', 'ObjectTypeController@massDestroy')->name('object-types.massDestroy');
    Route::resource('object-types', 'ObjectTypeController');

    // Documents
    Route::delete('documents/destroy', 'DocumentsController@massDestroy')->name('documents.massDestroy');
    Route::post('documents/media', 'DocumentsController@storeMedia')->name('documents.storeMedia');
    Route::post('documents/ckmedia', 'DocumentsController@storeCKEditorImages')->name('documents.storeCKEditorImages');
	Route::any('/documents/ajax-docs', 'DocumentsController@ajax_docs');
    Route::resource('documents', 'DocumentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/ObjectGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class ObjectGroup extends Model
{
    use SoftDeletes;

    public $table = 'object_groups';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/ObjectGroupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyObjectGroupRequest;
use App\Http\Requests\StoreObjectGroupRequest;
use App\Http\Requests\UpdateObjectGroupRequest;
use App\Models\ObjectGroup;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ObjectGroupController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('object_group_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $objectGroups = ObjectGroup::all();

        return view('admin.objectGroups.index', compact('objectGroups'));
    }

    public function create()
    {
        abort_if(Gate::denies('object_group_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.objectGroups.create');
    }

    public function store(StoreObjectGroupRequest $request)
    {
        $objectGroup = ObjectGroup::create($request->all());

        return redirect()->route('admin.object-groups.index');
    }

    public function edit(ObjectGroup $objectGroup)
    {
        abort_if(Gate::denies('object_group_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.objectGroups.edit', compact('objectGroup'));
    }

    public function update(UpdateObjectGroupRequest $request, ObjectGroup $objectGroup)
    {
        $objectGroup->update($request->all());

        return redirect()->route('admin.object-groups.index');
    }

    public function show(ObjectGroup $objectGroup)
    {
        abort_if(Gate::denies('object_group_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.objectGroups.show', compact('objectGroup'));
    }

    public function destroy(ObjectGroup $objectGroup)
    {
        abort_if(Gate::denies('object_group_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $objectGroup->delete();

        return back();
    }

    public function massDestroy(MassDestroyObjectGroupRequest $request)
    {
        ObjectGroup::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/objectGroups/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.objectGroup.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.object-groups.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.objectGroup.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.objectGroup.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/objectGroups/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.objectGroup.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.object-groups.update", [$objectGroup->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.objectGroup.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $objectGroup->name) }}" required>
                @if($errors->has('name'))
                    <span class="text-danger">{{ $errors->first('name') }}</span>
                @endif
                <span class="help-block">{{ trans('cruds.objectGroup.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/objectGroups/index.blade.php
@extends('layouts.admin')
@section('content')
@can('object_group_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.object-groups.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.objectGroup.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.objectGroup.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-ObjectGroup">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.objectGroup.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.objectGroup.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($objectGroups as $key => $objectGroup)
                        <tr data-entry-id="{{ $objectGroup->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $objectGroup->id ?? '' }}
                            </td>
                            <td>
                                {{ $objectGroup->name ?? '' }}
                            </td>
                            <td>
                                @can('object_group_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.object-groups.show', $objectGroup->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('object_group_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.object-groups.edit', $objectGroup->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('object_group_delete')
                                    <form action="{{ route('admin.object-groups.destroy', $objectGroup->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('object_group_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.object-groups.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-ObjectGroup:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/objectGroups/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.objectGroup.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.object-groups.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.objectGroup.fields.id') }}
                        </th>
                        <td>
                            {{ $objectGroup->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.objectGroup.fields.name') }}
                        </th>
                        <td>
                            {{ $objectGroup->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.object-groups.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection